### ISSUE TITLE
Pedir cotización del pedido y confirmarlo

### ISSUE THREAD

**Issue by herniadlf** [TP-Foodie/Foodie-Frontend-Mobile#26]
Una vez creado el pedido (cuando se selecciona producto y lugar), el flujo debería ser el siguiente:
1- Pantalla con el mapa que dibuje los deliveries cercanos (pegandole a available_deliveries) y que te pida seleccionar la dirección de entrega del pedido.
2- Cuando se confirma, se pide cotización al server.
3- Cuando el server responde, el usuario debe dar una confirmación final. 
3a- Si hay deliveries cercanos, el pedido se completa y se pasa a la etapa de entrega.
3b- Si no hay deliveries cercanos, el pedido debe quedar "pendiente" pero no puede avanzar.

**Comment by Azowyl** [comment]
Estaria genial si por aca metemos el metodo de pago, en principio habria un endpoint `/payment_methods` que da las opciones

**Comment by herniadlf** [comment]
Los payment method los estamos definiendo a la hora de crear el pedido. Quedaría agregar el costo al pedido una vez q lo confirma el usuario
