### ISSUE TITLE
Deshabilitar chat cuando no hay delivery asignado.

### ISSUE THREAD

**Issue by herniadlf** [TP-Foodie/Foodie-Frontend-Mobile#37]
Mirar el estado del pedido para permitir o no arrancar el chat. Sino te da la opción y tira un error.

**Comment by santiago-alvarezjulia** [comment]
Yo diria que el chat tiene q estar pero que no se pueden enviar mensajes, solo lectura

**Comment by herniadlf** [comment]
Si, me parece bien que quede como historial de ultima!
