### ISSUE TITLE
Realización pedido

### ISSUE THREAD

**Issue by Azowyl** [TP-Foodie/Foodie-Frontend-Mobile#8]
La aplicación debe permitir realizar un pedido indicando la fecha, el origen y el destino del mismo. Una vez indicado los datos del pedido, se deberá mostrar un mapa con los deliveries disponibles. El sistema asignará uno de forma automática mostrando la reputación y la posibilidad de confirmar o buscar otro delivery disponible.

**Comment by herniadlf** [comment]
Intentaremos respetar el siguiente workflow para una primera versión:
Paso 1: describir en texto **qué** es lo que se quiere pedir
Paso 2: definir dirección (**donde**) de lo que se quiere pedir
Paso 3: seleccionar la persona que lo entrega delivery

**Comment by Azowyl** [comment]
Aclaracion paso 2: el "donde" deberia ser el lugar que se definio en el walking skeleton, o sea deberia mandar en el post a `/orders`:
```python
{
    type: 'NT' # o 'FT',
    owner: id # del usuario,
    product: {
        name: 'salchipapa',
        place: id # del lugar
    }
}
```
